Lesson3
visumadness/TeachMeSkills-HW pull request #2
Opened 2023-08-06 22:21 UTC by visumadness

2023-08-07 15:09 UTC, gorodkoartem requested changes
Поправь, пожалуйста, код по комментам

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise1/E1.sln
> +﻿
Не нужно создавать отдельный солюшен под каждую таску в рамках одного ДЗ. Если ДЗ требует создания разных проектов, то нужно создать один солюшен и добавлять туда разные проекты.
Нужно это исправить

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise1/E1/Program.cs
> +int month = int.Parse(Console.ReadLine());
Лучше используй 
<code>if( int.TryParse(Console.ReadLine(), out var month))
{
//your code
}
else
{
// вывод сообщения на консоль о неправильном вводе
}</code>

В твоем решении если пользователь введет не число, то программа сломается, пользователь не получит адекватного сообщения о том, что он сделал не так. <code>TryParse</code> же вернет <code>true</code>, если получилось из строки сделать число и запишет в переменную month значение. Если строка неправильного формата, то вернется <code>false</code>.

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise1/E1/Program.cs
> +
лишний пробел

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise1/E1/Program.cs
> +        Console.WriteLine("Это Зима");
Получается такая ситуация, что у тебя в каждой "ветке" выполнения кода вызывается повторяющаяся логика - вызов метода <code>Console.WriteLine</code>
В данном случае ты можешь объявить переменную "userOutput" и вместо вывода на консоль сообщения по коду, просто присваивай этой переменной нужное значение. В таком случае перед окончанием программы ты сможешь вывести на консоль значение переменной <code>userOutpt</code>.
Таким образом код станет понятнее. Плюс потенциально если у тебя добавится необходимость записать сообщение не только в консоль, а еще что-нибудь с ним сделать, то ты это сделаешь в одном месте, а не по всему коду.

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise2/Exercise2/Program.cs
> +if (month == 12 || month == 1 || month == 2)
Неплохой подход с return внутри условного выражения. Но задание было использовать if else if. Лайк за подход, который на занятии не обсуждали, но будь внимательнее)
Исправлять не нужно

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise3/Exercise3/Program.cs
> +if (isInteger)
здесь можно было не выделять отдельную переменную, тк она по коду дальше не используется, а поместить внутрь ифа выражение <code>int.TryParse(strNum, out int numValue)</code>.

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise3/Exercise3/Program.cs
> +    numValue %= 2;
Так лучше не делать. Каждая переменная имеет свое значение. Например, переменная numValue в этом контексте, это ввод пользователя, преобразованный в число. После операции <code>numValue %= 2;</code> в переменной numValue уже лежит что-то другое. Вместо этого в If ниже лучше было бы записать <code>if(numValue % 2 == 0)</code>.

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise4/Exercise4/Program.cs
> +var temp = Convert.ToInt32(Console.ReadLine());
Такой метод без дополнительных проверок ведет к тем же проблемам, что и в таске 1. Лучше используй подход с int.TryParse

2023-08-07 15:09 UTC, gorodkoartem commented on Lesson3/Exercise4/Exercise4/Program.cs
> +Console.WriteLine("Вы ввели неверное или несуществующее значение");
Этот код никогда не выполнится - те лишний. Ты ифами покрываешь все возможные значения переменной temp.

2023-08-07 18:31 UTC, visumadness commented on Lesson3/Exercise1/E1/Program.cs
> +
removed space

2023-08-07 18:32 UTC, visumadness commented on Lesson3/Exercise1/E1/Program.cs
> +        Console.WriteLine("Это Зима");
corrected

2023-08-07 18:33 UTC, visumadness commented on Lesson3/Exercise3/Exercise3/Program.cs
> +if (isInteger)
corrected

2023-08-07 18:34 UTC, visumadness commented on Lesson3/Exercise3/Exercise3/Program.cs
> +    numValue %= 2;
corrected

2023-08-07 18:34 UTC, visumadness commented on Lesson3/Exercise4/Exercise4/Program.cs
> +var temp = Convert.ToInt32(Console.ReadLine());
corrected

2023-08-07 18:35 UTC, visumadness commented on Lesson3/Exercise4/Exercise4/Program.cs
> +Console.WriteLine("Вы ввели неверное или несуществующее значение");
fixed

2023-08-08 13:55 UTC, gorodkoartem commented on Lesson3/Exercise1/Exercise1/E1.cs
> +        userOutput("Это зима");
Классно, что знаешь про экшены! Но идея была сильно проще - сделать переменную стринговую userOutput и в крнце программы ее вывести. Твой подход хороший, если нужно будет добавить вывод еще и в файл куда-то, то на userOutput можно повесить еще один метод и проблема решена.

2023-08-08 13:57 UTC, gorodkoartem commented on Lesson3/Exercise1/Exercise1/E1.cs
> +string strMonth = Console.ReadLine();
Отлично! Единственный нюанс, что в .net не принято ссылаться на тип в имени переменной, в данном случае прокатывает, но лучше этого избегать.

2023-08-08 13:57 UTC, gorodkoartem commented on Lesson3/Exercise1/Exercise1/E1.cs
> +string strMonth = Console.ReadLine();
* править не нужно, просто совет на будущее

2023-08-08 14:01 UTC, gorodkoartem commented on Lesson3/Exercise1/Exercise1/E1.cs
> +bool tryMonth = int.TryParse(strMonth, out int numMonth);
Название переменной подкачало. Лучше <code>parsingSucceeded</code>. 

*правь по желанию

2023-08-08 14:01 UTC, gorodkoartem approved these changes

2023-08-08 14:11 UTC, merged