Lesson4
visumadness/TeachMeSkills-HW pull request #3
Opened 2023-08-12 23:41 UTC by visumadness

2023-08-14 16:21 UTC, gorodkoartem requested changes

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/.vs/Lesson4/DesignTimeBuild/.dtbcache.v2
Файлов из папки .vs здесь быть не должно!
удали их и поправь гитигнор файл (можно даже в рамках этого ПРа), чтобы эти файлики у тебя гит не отслеживал

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +Array.Sort(array);
Если использовать методы из типа Array, то лучше использовать в данном случае Array.Max.
Но задание было реализовать алгоритм, то есть самому найти максимальный элемент.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +for (int i = 0; i < arrayZub.Length; i++)
Задание было написать методы. В методе должно было быть только вычисление среднего арифметического, заполнение массива рандомными числами и вывод на консоль должны быть отделены от вычисления среднего арифметического.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +    {
Это явно лишний пустой блок.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +    a[0] = 0;
Решение правильное, но если n < 2, то код не будет работать, нужно дополнить решение.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +    int[] a = new int[number];
Так переменные можно называть только для тестовых целей. В ПРе должны быть полные имена переменных.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +foreach(var elements in b)
Почему elements? Множественное число здесь сильно сбивает с толку.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise1/E1.cs
> +var b = Fib(10);
Нейминг переменных нужно поправить по всему ДЗ!

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise2/E2.cs
> +﻿Action<string> userOutput = Console.WriteLine;
Ты здесь юзер аутпут по назначению не используешь. В предыдущем задании это работало, тк вместо постоянного вызова Console.WriteLine() ты использовал userOutput делегат. Здесь же ты где-то используешь userOutput , где-то Console.WriteLine(). Лучше пока отказаться от идеи с userOutput, есть ощущение, что она тебя только запутывает.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise2/E2.cs
> +    Console.Write("Enter the first number:");
по заданию пользователь должен ввести сразу всю строку, после чего ты эту строку должен разобрать.

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise2/E2.cs
> +    if (oper == '+')
switch тут смотрелся бы лучше

2023-08-14 16:21 UTC, gorodkoartem commented on Lesson4/Exercise2/E2.cs
> +    again = Convert.ToChar(Console.ReadLine());
А что если я введу больше одного символа? Приложение ляжет с ошибкой. Можешь вместо Console.ReadLine() использовать Console.Read()

2023-08-20 11:31 UTC, gorodkoartem approved these changes
Всё классно, как поправишь комменты, можешь заливать в мейн)

2023-08-20 11:31 UTC, gorodkoartem commented on Lesson4/Task1/Task1.cs
> +static int[] GenerateFibonacciSequence(int FibonacciSequence)
аргументы должны начинаться с маленькой буквы

2023-08-20 11:31 UTC, gorodkoartem commented on Lesson4/Task3/Task3.cs
Здесь для красоты можешь вынести заполнение массива рандомами и вывод массива на экран в отдельные методы

2023-08-20 14:30 UTC, visumadness commented on Lesson4/Task3/Task3.cs
Fixed

2023-08-20 14:31 UTC, visumadness commented on Lesson4/Task1/Task1.cs
> +static int[] GenerateFibonacciSequence(int FibonacciSequence)
Fixed

2023-08-20 14:31 UTC, merged